### ISSUE TITLE
Update to JMS Serializer bundle 1.0

### ISSUE THREAD

**Issue by christophercr** [adrotec/AdrotecWebApiBundle#3]
Hello,

Can the dependency to the JMS serializer bundle be updated to the latest version (v1.0) to make use of the latest features of such bundle?

A couple of months ago, the dependency to the JMS serializer was updated in breeze.server.php to the v1.0. But as soon as you use breeze.server.php and adrotectwebapibundle you get into troubles because there are conflicts in the version of the serializer that they require (0.13.0 and 1.0).

Regards.

**Comment by safrazik** [comment]
Updated on master branch. Can you try and see if it's working fine?

**Comment by christophercr** [comment]
Hi,

I've tried and so far it works fine for me. So I think it is ok to release a new version for this.

I think a new release for the breeze.server.php is needed, cause even though the dependency there on the serializer has been upgraded to 1.0, there is no actual release containing such upgrade. I've commented the corresponding issue in that project.

Regards.

**Comment by safrazik** [comment]
done!

**Comment by christophercr** [comment]
Thanks!
